//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexoMarket.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamiliaPermiso
    {
        public int Id_Familia { get; set; }
        public int Id_Permiso { get; set; }
        public string Nombre { get; set; }
    
        public virtual Permiso Permiso { get; set; }
    }
}
