//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexoMarket.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.EstadisticaServiceSoap")]
    public interface EstadisticaServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTopProductos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetTopProductos(System.Data.DataTable datosSP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTopProductos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetTopProductosAsync(System.Data.DataTable datosSP);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EstadisticaServiceSoapChannel : ServiceReference1.EstadisticaServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EstadisticaServiceSoapClient : System.ServiceModel.ClientBase<ServiceReference1.EstadisticaServiceSoap>,   ServiceReference1.EstadisticaServiceSoap {
        
        public EstadisticaServiceSoapClient() {
        }
        
        public EstadisticaServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EstadisticaServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstadisticaServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstadisticaServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetTopProductos(System.Data.DataTable datosSP) {
            return base.Channel.GetTopProductos(datosSP);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetTopProductosAsync(System.Data.DataTable datosSP) {
            return base.Channel.GetTopProductosAsync(datosSP);
        }
    }
}
